/**
 * Pruned SpacetimeDB bindings for the BitCraft region module, as mirrored by
 * relay.bitjita.com (`bitcraft-live-{N}` per live region).
 *
 * The table/type files come from the `vendor/bitcraft-bindings` git submodule
 * (https://github.com/BitCraftToolBox/BitCraft_Bindings, branch `ts-region`,
 * generated by spacetimedb CLI 1.3.0). Only this index is hand-written: the
 * generated one registers all 274 region tables, which would drag the whole
 * schema into the client bundle. The server only ever sends rows for
 * subscribed queries, so registering the subset we subscribe to is
 * sufficient. The generated table files import their index as `.` — a Vite
 * resolve hook in vite.config.ts redirects that back here so the full index
 * never enters the bundle.
 *
 * The relay is read-only and rejects CallReducer, so no reducers are
 * registered and `Reducer` is `never`.
 *
 * To update after a game patch: bump the submodule
 * (`git submodule update --remote vendor/bitcraft-bindings`) and commit the
 * new pointer. If the game schema added a type one of our tables references,
 * add its import here.
 */

/* eslint-disable */
/* tslint:disable */
// @ts-nocheck
import {
  DbConnectionBuilder,
  DbConnectionImpl,
  SubscriptionBuilderImpl,
  type ErrorContextInterface,
  type Event,
  type EventContextInterface,
  type ReducerEventContextInterface,
  type SubscriptionEventContextInterface,
} from "@clockworklabs/spacetimedb-sdk";

import { EnemyMobMonitorStateTableHandle } from "../../../vendor/bitcraft-bindings/src/enemy_mob_monitor_state_table";
import { LocationStateTableHandle } from "../../../vendor/bitcraft-bindings/src/location_state_table";
import { MobileEntityStateTableHandle } from "../../../vendor/bitcraft-bindings/src/mobile_entity_state_table";
import { PlayerUsernameStateTableHandle } from "../../../vendor/bitcraft-bindings/src/player_username_state_table";
import { ResourceGrowthTimerTableHandle } from "../../../vendor/bitcraft-bindings/src/resource_growth_timer_table";
import { ResourceStateTableHandle } from "../../../vendor/bitcraft-bindings/src/resource_state_table";
import { SignedInPlayerStateTableHandle } from "../../../vendor/bitcraft-bindings/src/signed_in_player_state_table";

import { EnemyMobMonitorState } from "../../../vendor/bitcraft-bindings/src/enemy_mob_monitor_state_type";
import { GrowthTimer } from "../../../vendor/bitcraft-bindings/src/growth_timer_type";
import { LocationState } from "../../../vendor/bitcraft-bindings/src/location_state_type";
import { MobileEntityState } from "../../../vendor/bitcraft-bindings/src/mobile_entity_state_type";
import { PlayerUsernameState } from "../../../vendor/bitcraft-bindings/src/player_username_state_type";
import { ResourceState } from "../../../vendor/bitcraft-bindings/src/resource_state_type";
import { SignedInPlayerState } from "../../../vendor/bitcraft-bindings/src/signed_in_player_state_type";

export { EnemyMobMonitorState, GrowthTimer, LocationState, MobileEntityState, PlayerUsernameState, ResourceState, SignedInPlayerState };
export { EnemyType } from "../../../vendor/bitcraft-bindings/src/enemy_type_type";
export { OffsetCoordinatesSmallMessage } from "../../../vendor/bitcraft-bindings/src/offset_coordinates_small_message_type";

export const REMOTE_MODULE = {
  tables: {
    mobile_entity_state: {
      tableName: "mobile_entity_state",
      rowType: MobileEntityState.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: MobileEntityState.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    signed_in_player_state: {
      tableName: "signed_in_player_state",
      rowType: SignedInPlayerState.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: SignedInPlayerState.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    player_username_state: {
      tableName: "player_username_state",
      rowType: PlayerUsernameState.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: PlayerUsernameState.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    enemy_mob_monitor_state: {
      tableName: "enemy_mob_monitor_state",
      rowType: EnemyMobMonitorState.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: EnemyMobMonitorState.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    resource_state: {
      tableName: "resource_state",
      rowType: ResourceState.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: ResourceState.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    location_state: {
      tableName: "location_state",
      rowType: LocationState.getTypeScriptAlgebraicType(),
      primaryKey: "entityId",
      primaryKeyInfo: {
        colName: "entityId",
        colType: LocationState.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
    resource_growth_timer: {
      tableName: "resource_growth_timer",
      rowType: GrowthTimer.getTypeScriptAlgebraicType(),
      primaryKey: "scheduledId",
      primaryKeyInfo: {
        colName: "scheduledId",
        colType: GrowthTimer.getTypeScriptAlgebraicType().product.elements[0].algebraicType,
      },
    },
  },
  reducers: {},
  versionInfo: {
    cliVersion: "1.3.0",
  },
  eventContextConstructor: (imp: DbConnectionImpl, event: Event<Reducer>) => {
    return {
      ...(imp as DbConnection),
      event
    }
  },
  dbViewConstructor: (imp: DbConnectionImpl) => {
    return new RemoteTables(imp);
  },
  reducersConstructor: (imp: DbConnectionImpl, setReducerFlags: SetReducerFlags) => {
    return new RemoteReducers(imp, setReducerFlags);
  },
  setReducerFlagsConstructor: () => {
    return new SetReducerFlags();
  }
}

/** The relay is read-only: no reducers exist client-side. */
export type Reducer = never;

export class RemoteReducers {
  constructor(private connection: DbConnectionImpl, private setCallReducerFlags: SetReducerFlags) {}
}

export class SetReducerFlags {}

export class RemoteTables {
  constructor(private connection: DbConnectionImpl) {}

  get mobileEntityState(): MobileEntityStateTableHandle {
    return new MobileEntityStateTableHandle(this.connection.clientCache.getOrCreateTable<MobileEntityState>(REMOTE_MODULE.tables.mobile_entity_state));
  }

  get signedInPlayerState(): SignedInPlayerStateTableHandle {
    return new SignedInPlayerStateTableHandle(this.connection.clientCache.getOrCreateTable<SignedInPlayerState>(REMOTE_MODULE.tables.signed_in_player_state));
  }

  get playerUsernameState(): PlayerUsernameStateTableHandle {
    return new PlayerUsernameStateTableHandle(this.connection.clientCache.getOrCreateTable<PlayerUsernameState>(REMOTE_MODULE.tables.player_username_state));
  }

  get enemyMobMonitorState(): EnemyMobMonitorStateTableHandle {
    return new EnemyMobMonitorStateTableHandle(this.connection.clientCache.getOrCreateTable<EnemyMobMonitorState>(REMOTE_MODULE.tables.enemy_mob_monitor_state));
  }

  get resourceState(): ResourceStateTableHandle {
    return new ResourceStateTableHandle(this.connection.clientCache.getOrCreateTable<ResourceState>(REMOTE_MODULE.tables.resource_state));
  }

  get locationState(): LocationStateTableHandle {
    return new LocationStateTableHandle(this.connection.clientCache.getOrCreateTable<LocationState>(REMOTE_MODULE.tables.location_state));
  }

  get resourceGrowthTimer(): ResourceGrowthTimerTableHandle {
    return new ResourceGrowthTimerTableHandle(this.connection.clientCache.getOrCreateTable<GrowthTimer>(REMOTE_MODULE.tables.resource_growth_timer));
  }
}

export class SubscriptionBuilder extends SubscriptionBuilderImpl<RemoteTables, RemoteReducers, SetReducerFlags> { }

export class DbConnection extends DbConnectionImpl<RemoteTables, RemoteReducers, SetReducerFlags> {
  static builder = (): DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext> => {
    return new DbConnectionBuilder<DbConnection, ErrorContext, SubscriptionEventContext>(REMOTE_MODULE, (imp: DbConnectionImpl) => imp as DbConnection);
  }
  subscriptionBuilder = (): SubscriptionBuilder => {
    return new SubscriptionBuilder(this);
  }
}

// Context types come from the generated index so callbacks passed to the
// table handles (whose signatures reference it) typecheck. The generated
// index is types-only here — the Vite hook keeps it out of the bundle.
export type {
  EventContext,
  ReducerEventContext,
  SubscriptionEventContext,
  ErrorContext,
} from "../../../vendor/bitcraft-bindings/src/index";
