name: Update data

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
      with:
        submodules: true
    - name: Run script
      working-directory: scripts
      run: |
        npx tsx update-resource-index.ts
    - name: Update relay bindings submodule
      run: git submodule update --remote vendor/bitcraft-bindings
    - name: Push changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add -A

        if ! git diff --cached --quiet; then
          git commit -m "chore: update resource index and relay bindings"
          git push origin
        fi
